package views;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;

public class TheFrame extends javax.swing.JFrame {

    public void setActorsModel(ListModel model) {
        actors.setModel(model);
    }
    public void setMoviesModel(ListModel model) {
        movies.setModel(model);
    }
    
    public void setMovieRenderer(ListCellRenderer r) {
        movies.setCellRenderer(r);
    }
    public void setActorRenderer(ListCellRenderer r) {
        actors.setCellRenderer(r);
    }
    
    public void addMoviesListSelectionListener(ListSelectionListener listerner) {
        movies.addListSelectionListener(listerner);
    }
    public models.Movie getSelectedMovie() {
        return (models.Movie) movies.getSelectedValue();
    }
    public void setInfoText(String text) {
        info.setText(text);
        info.setCaretPosition(0);
    }
    
    public void addActorsListSelectionListener(ListSelectionListener listener) {
        actors.addListSelectionListener(listener);
    }
    public models.Actor getSelectedActor() {
        return (models.Actor) actors.getSelectedValue();
    }
    public void setInfoActorText(String text) {
        infoActor.setText(text);
        infoActor.setCaretPosition(0);
    }
    
    public void addJoinActorActionListener (ActionListener listener) {
        joinActor.addActionListener(listener);
    }
    public void addUnjoinActorActionListener(ActionListener listener) {
        unjoinActor.addActionListener(listener);
    }
//    public void addClearActorActionListener(ActionListener listener) {
//        clearActor.addActionListener(listener);
//    }
//    public void clearActorSelection() {
//        actors.clearSelection();
//    }
    
    public void addAddMovieActionListener(ActionListener listener) {
        addMovie.addActionListener(listener);
    }
    public void addEditDescriptionActionListener(ActionListener listener) {
        editDescription.addActionListener(listener);
    }
    public void addAddActorActionListener(ActionListener listener) {
        addActor.addActionListener(listener);
    }
    public void addRemoveActorActionListener(ActionListener listener) {
        removeActor.addActionListener(listener);
    }
    public void addRemoveMovieActionListener(ActionListener listener) {
        removeMovie.addActionListener(listener);
    }
    
    
    public TheFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        actors = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        movies = new javax.swing.JList();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        joinActor = new javax.swing.JButton();
        unjoinActor = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoActor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addActor = new javax.swing.JMenuItem();
        removeActor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addMovie = new javax.swing.JMenuItem();
        editDescription = new javax.swing.JMenuItem();
        removeMovie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        actors.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        actors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(actors);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        movies.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        movies.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(movies);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jlabel1.setText("Actors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jlabel1, gridBagConstraints);

        jlabel2.setText("Movies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jlabel2, gridBagConstraints);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        info.setEditable(false);
        info.setColumns(20);
        info.setLineWrap(true);
        info.setRows(5);
        info.setWrapStyleWord(true);
        jScrollPane3.setViewportView(info);

        bottomPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        joinActor.setText("Join Actor");
        jPanel1.add(joinActor);

        unjoinActor.setText("Un-join Actor");
        jPanel1.add(unjoinActor);

        bottomPanel.add(jPanel1, java.awt.BorderLayout.LINE_END);

        infoActor.setEditable(false);
        infoActor.setColumns(20);
        infoActor.setLineWrap(true);
        infoActor.setRows(5);
        jScrollPane4.setViewportView(infoActor);

        bottomPanel.add(jScrollPane4, java.awt.BorderLayout.LINE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(bottomPanel, gridBagConstraints);

        jMenu1.setText("Actor");

        addActor.setText("Add Actor");
        jMenu1.add(addActor);

        removeActor.setText("Remove Actor");
        jMenu1.add(removeActor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movie");

        addMovie.setText("Add Movie");
        jMenu2.add(addMovie);

        editDescription.setText("Edit Description");
        jMenu2.add(editDescription);

        removeMovie.setText("Remove Movie");
        jMenu2.add(removeMovie);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList actors;
    private javax.swing.JMenuItem addActor;
    private javax.swing.JMenuItem addMovie;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem editDescription;
    private javax.swing.JTextArea info;
    private javax.swing.JTextArea infoActor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JButton joinActor;
    private javax.swing.JList movies;
    private javax.swing.JMenuItem removeActor;
    private javax.swing.JMenuItem removeMovie;
    private javax.swing.JButton unjoinActor;
    // End of variables declaration//GEN-END:variables
}
